services:
  - type: web
    name: telegram-gemini-bot
    env: docker
    buildCommand: |
      chmod +x mvnw
      ./mvnw clean package -DskipTests
      docker build -t telegram-bot .
    startCommand: java -jar target/ChatBot_for_TG-0.0.1-SNAPSHOT.jar
    envVars:
      - key: BOT_USERNAME
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
